In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
def ignore_warn(*args, **kwargs):
    pass
warnings.warn = ignore_warn

## Importing cleaned datasets

In [2]:
df_cleaned_compustat = pd.read_csv('data/Cleaned_Compustat.csv', usecols=['fyear', 'cusip', 'gsector', 'ggroup', 'gind', 'gsubind', 'epspx', 'bkvlps'])
df_cleaned_compustat

,cusip,gsector,ggroup,gind,gsubind,fyear,epspx,bkvlps
0,000165,25.0,2530.0,253010.0,25301040.0,1984,0.40,2.1925
1,000165,25.0,2530.0,253010.0,25301040.0,1985,0.32,2.5118
2,000354,25.0,2550.0,255040.0,25504040.0,1983,0.44,0.9443
3,000354,25.0,2550.0,255040.0,25504040.0,1984,0.49,2.2717
4,000354,25.0,2550.0,255040.0,25504040.0,1985,0.14,2.4160
...,...,...,...,...,...,...,...,...
290704,21077C,25.0,2550.0,255020.0,25502020.0,2019,-0.35,-12.3599
290705,21077C,25.0,2550.0,255020.0,25502020.0,2020,-0.22,-14.6777
290706,21077C,25.0,2550.0,255020.0,25502020.0,2021,-1.27,1.7496
290707,Y4600W,45.0,4510.0,451030.0,45103010.0,2019,0.79,43983.0000
290708,Y4600W,45.0,4510.0,451030.0,45103010.0,2020,0.86,55947.0000

In [3]:
df_cleaned_crsp = pd.read_csv('data/Cleaned_Crsp.csv')
df_cleaned_crsp

,date,fyear,cusip,permno,prc,shrout,mktcap,ret
0,1986-03-31,1986,683916,10000,3.25000,3680.0,1.196000e+04,-0.257143
1,1986-04-30,1986,683916,10000,4.43750,3680.0,1.633000e+04,0.365385
2,1986-05-30,1986,683916,10000,4.00000,3793.0,1.517200e+04,-0.098592
3,1986-06-30,1986,683916,10000,3.10938,3793.0,1.179388e+04,-0.222656
4,1986-07-31,1986,683916,10000,3.09375,3793.0,1.173459e+04,-0.005025
...,...,...,...,...,...,...,...,...
3538897,2020-08-31,2020,88160R,93436,1430.76001,186362.0,2.666393e+08,0.325011
3538898,2020-09-30,2020,88160R,93436,498.32001,931809.0,4.643391e+08,0.741452
3538899,2020-10-30,2020,88160R,93436,429.01001,948000.0,4.067015e+08,-0.139087
3538900,2020-11-30,2020,88160R,93436,388.04001,947901.0,3.678235e+08,-0.095499
3538901,2020-12-31,2020,88160R,93436,567.59998,947901.0,5.380286e+08,0.462736

## Merging the datasets

In [4]:
df_final = df_cleaned_crsp.merge(df_cleaned_compustat, left_on=['cusip','fyear'], right_on=['cusip','fyear'], how='left')
df_final

,date,fyear,cusip,permno,prc,shrout,mktcap,ret,gsector,ggroup,gind,gsubind,epspx,bkvlps
0,1986-03-31,1986,683916,10000,3.25000,3680.0,1.196000e+04,-0.257143,25.0,2520.0,252020.0,25202010.0,-0.18,-0.1186
1,1986-04-30,1986,683916,10000,4.43750,3680.0,1.633000e+04,0.365385,25.0,2520.0,252020.0,25202010.0,-0.18,-0.1186
2,1986-05-30,1986,683916,10000,4.00000,3793.0,1.517200e+04,-0.098592,25.0,2520.0,252020.0,25202010.0,-0.18,-0.1186
3,1986-06-30,1986,683916,10000,3.10938,3793.0,1.179388e+04,-0.222656,25.0,2520.0,252020.0,25202010.0,-0.18,-0.1186
4,1986-07-31,1986,683916,10000,3.09375,3793.0,1.173459e+04,-0.005025,25.0,2520.0,252020.0,25202010.0,-0.18,-0.1186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3540689,2020-08-31,2020,88160R,93436,1430.76001,186362.0,2.666393e+08,0.325011,25.0,2510.0,251020.0,25102010.0,-4.92,36.5635
3540690,2020-09-30,2020,88160R,93436,498.32001,931809.0,4.643391e+08,0.741452,25.0,2510.0,251020.0,25102010.0,-4.92,36.5635
3540691,2020-10-30,2020,88160R,93436,429.01001,948000.0,4.067015e+08,-0.139087,25.0,2510.0,251020.0,25102010.0,-4.92,36.5635
3540692,2020-11-30,2020,88160R,93436,388.04001,947901.0,3.678235e+08,-0.095499,25.0,2510.0,251020.0,25102010.0,-4.92,36.5635
3540693,2020-12-31,2020,88160R,93436,567.59998,947901.0,5.380286e+08,0.462736,25.0,2510.0,251020.0,25102010.0,-4.92,36.5635

In [5]:
df_final[df_final['fyear']>2010].to_csv('data/CleanData_Merged.csv', index=False)

In [6]:
del(df_final)

In [7]:
from IPython.display import display_html
def restartkernel() :
    display_html("<script>Jupyter.notebook.kernel.restart()</script>",raw=True)